dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: my3
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: mysprinh
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: springpr22
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: springprj
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
